### PR TITLE
add country to firstboot

### PR DESCRIPTION
**Pull request by macmoritz**
This PR adds the country variable to wifi-config.txt, which gets set by `iw reg set $COUNTRY`  
It is a good idea to set the wifi country, this makes sure the wifi adapter sends on (all) allowed frequencies, which leads to the best wireless communication possible.

### CODE REVIEW

**Comment by macmoritz** [comment]
Sorry for commiting an unverified commit, something went wrong in my settings. I hope this is not a deal-breaker.

**Comment by ToKe79** [comment]
Thank you for your PR, @macmoritz!
No problem with the missing signature.
Can you please confirm that you tested this on real hardware and it does not cause any issues - e.g. the system does not hang / behaves unexpectedly.

**Comment by macmoritz** [comment]
You're welcome. 
Glad to hear, that the missing signature is no big deal!

I was not able to build the image after my changes, but the relevant file is the firstboot.sh. This change was successfully tested manually (writing the latest version, changing the file, boot).
Hope this satisfies your concerns.

**Comment by ToKe79** [comment]
Yes, that should be enough.
Thank you!

**Pull request merged**
